/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Article

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param id 
 * @param articleId 
 * @param article 
 * @param name 
 * @param referenceUrl 
 * @param order 
 */

data class ArticleSource (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("articleId")
    val articleId: java.util.UUID? = null,
    @SerializedName("article")
    val article: Article? = null,
    @SerializedName("name")
    val name: kotlin.String? = null,
    @SerializedName("referenceUrl")
    val referenceUrl: kotlin.String? = null,
    @SerializedName("order")
    val order: kotlin.Int? = null
)

