/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.DealPackage
import org.openapitools.client.models.Service

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param dealPackageId 
 * @param dealPackage 
 * @param serviceId 
 * @param service 
 * @param order 
 */

data class DealPackageService (
    @SerializedName("dealPackageId")
    val dealPackageId: java.util.UUID? = null,
    @SerializedName("dealPackage")
    val dealPackage: DealPackage? = null,
    @SerializedName("serviceId")
    val serviceId: java.util.UUID? = null,
    @SerializedName("service")
    val service: Service? = null,
    @SerializedName("order")
    val order: kotlin.Int? = null
)

