/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AuditableEntity
import org.openapitools.client.models.DealPackageServiceItemViewModel
import org.openapitools.client.models.RefundPolicy

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param dealId 
 * @param dealName 
 * @param hospitalId 
 * @param hospitalName 
 * @param refundPolicy 
 * @param additionalServices 
 * @param accomodation 
 * @param transfer 
 * @param bonus 
 * @param price 
 * @param serviceCount 
 * @param dealPackageServices 
 * @param auditableEntity 
 */

data class DealPackageItemViewModel (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "dealId")
    val dealId: java.util.UUID? = null,
    @Json(name = "dealName")
    val dealName: kotlin.String? = null,
    @Json(name = "hospitalId")
    val hospitalId: java.util.UUID? = null,
    @Json(name = "hospitalName")
    val hospitalName: kotlin.String? = null,
    @Json(name = "refundPolicy")
    val refundPolicy: RefundPolicy? = null,
    @Json(name = "additionalServices")
    val additionalServices: kotlin.String? = null,
    @Json(name = "accomodation")
    val accomodation: kotlin.String? = null,
    @Json(name = "transfer")
    val transfer: kotlin.String? = null,
    @Json(name = "bonus")
    val bonus: kotlin.String? = null,
    @Json(name = "price")
    val price: kotlin.Double? = null,
    @Json(name = "serviceCount")
    val serviceCount: kotlin.Int? = null,
    @Json(name = "dealPackageServices")
    val dealPackageServices: kotlin.collections.List<DealPackageServiceItemViewModel>? = null,
    @Json(name = "auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

