/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Article
import org.openapitools.client.models.AuditableEntity
import org.openapitools.client.models.AwardViewModel
import org.openapitools.client.models.DoctorCertificateItemViewModel
import org.openapitools.client.models.DoctorEducationItemViewModel
import org.openapitools.client.models.DoctorPortfolioItemViewModel
import org.openapitools.client.models.DoctorReviewItemViewModel
import org.openapitools.client.models.DoctorSpecialtyItemViewModel
import org.openapitools.client.models.Gender
import org.openapitools.client.models.HospitalAffiliationViewModel
import org.openapitools.client.models.MediaViewModel
import org.openapitools.client.models.UserLanguageViewModel
import org.openapitools.client.models.UserLocationViewModel

import com.google.gson.annotations.SerializedName
/**
 * 
 * @param slug 
 * @param startPracticeDate 
 * @param yearOfExperience 
 * @param overview 
 * @param consultationEnabled 
 * @param consultationFee 
 * @param doctorReviews 
 * @param doctorEducations 
 * @param doctorPortfolios 
 * @param doctorSpecialties 
 * @param doctorCertificates 
 * @param doctorAffiliations 
 * @param articles 
 * @param awards 
 * @param medias 
 * @param userType 
 * @param languages 
 * @param locations 
 * @param id 
 * @param userName 
 * @param firstName 
 * @param lastName 
 * @param fullname 
 * @param phone 
 * @param email 
 * @param photo 
 * @param photoThumbnail 
 * @param gender 
 * @param dateOfBirth 
 * @param auditableEntity 
 */

data class DoctorViewModel (
    @SerializedName("slug")
    val slug: kotlin.String? = null,
    @SerializedName("startPracticeDate")
    val startPracticeDate: java.time.LocalDateTime? = null,
    @SerializedName("yearOfExperience")
    val yearOfExperience: kotlin.Double? = null,
    @SerializedName("overview")
    val overview: kotlin.String? = null,
    @SerializedName("consultationEnabled")
    val consultationEnabled: kotlin.Boolean? = null,
    @SerializedName("consultationFee")
    val consultationFee: kotlin.Double? = null,
    @SerializedName("doctorReviews")
    val doctorReviews: kotlin.Array<DoctorReviewItemViewModel>? = null,
    @SerializedName("doctorEducations")
    val doctorEducations: kotlin.Array<DoctorEducationItemViewModel>? = null,
    @SerializedName("doctorPortfolios")
    val doctorPortfolios: kotlin.Array<DoctorPortfolioItemViewModel>? = null,
    @SerializedName("doctorSpecialties")
    val doctorSpecialties: kotlin.Array<DoctorSpecialtyItemViewModel>? = null,
    @SerializedName("doctorCertificates")
    val doctorCertificates: kotlin.Array<DoctorCertificateItemViewModel>? = null,
    @SerializedName("doctorAffiliations")
    val doctorAffiliations: kotlin.Array<HospitalAffiliationViewModel>? = null,
    @SerializedName("articles")
    val articles: kotlin.Array<Article>? = null,
    @SerializedName("awards")
    val awards: kotlin.Array<AwardViewModel>? = null,
    @SerializedName("medias")
    val medias: kotlin.Array<MediaViewModel>? = null,
    @SerializedName("userType")
    val userType: kotlin.String? = null,
    @SerializedName("languages")
    val languages: kotlin.Array<UserLanguageViewModel>? = null,
    @SerializedName("locations")
    val locations: kotlin.Array<UserLocationViewModel>? = null,
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("userName")
    val userName: kotlin.String? = null,
    @SerializedName("firstName")
    val firstName: kotlin.String? = null,
    @SerializedName("lastName")
    val lastName: kotlin.String? = null,
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,
    @SerializedName("phone")
    val phone: kotlin.String? = null,
    @SerializedName("email")
    val email: kotlin.String? = null,
    @SerializedName("photo")
    val photo: kotlin.String? = null,
    @SerializedName("photoThumbnail")
    val photoThumbnail: kotlin.String? = null,
    @SerializedName("gender")
    val gender: Gender? = null,
    @SerializedName("dateOfBirth")
    val dateOfBirth: java.time.LocalDateTime? = null,
    @SerializedName("auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

