/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param id 
 * @param doctorId 
 * @param doctorName 
 * @param institution 
 * @param qualification 
 * @param graduationDate 
 * @param graduationYear 
 * @param graduationMonth 
 */

data class DoctorEducationViewModel (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("doctorId")
    val doctorId: java.util.UUID? = null,
    @SerializedName("doctorName")
    val doctorName: kotlin.String? = null,
    @SerializedName("institution")
    val institution: kotlin.String? = null,
    @SerializedName("qualification")
    val qualification: kotlin.String? = null,
    @SerializedName("graduationDate")
    val graduationDate: java.time.LocalDateTime? = null,
    @SerializedName("graduationYear")
    val graduationYear: kotlin.Int? = null,
    @SerializedName("graduationMonth")
    val graduationMonth: kotlin.Int? = null
)

