/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Doctor

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param doctorId 
 * @param doctor 
 * @param name 
 * @param normalizedName 
 * @param description 
 * @param photoBefore 
 * @param photoBeforeThumbnail 
 * @param photoAfter 
 * @param photoAfterThumbnail 
 */

data class DoctorPortfolio (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "doctorId")
    val doctorId: java.util.UUID? = null,
    @Json(name = "doctor")
    val doctor: Doctor? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "normalizedName")
    val normalizedName: kotlin.String? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "photoBefore")
    val photoBefore: kotlin.String? = null,
    @Json(name = "photoBeforeThumbnail")
    val photoBeforeThumbnail: kotlin.String? = null,
    @Json(name = "photoAfter")
    val photoAfter: kotlin.String? = null,
    @Json(name = "photoAfterThumbnail")
    val photoAfterThumbnail: kotlin.String? = null
)

