/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param id 
 * @param code 
 * @param name 
 * @param description 
 * @param published 
 * @param order 
 */

data class LanguageItemViewModel (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("code")
    val code: kotlin.String? = null,
    @SerializedName("name")
    val name: kotlin.String? = null,
    @SerializedName("description")
    val description: kotlin.String? = null,
    @SerializedName("published")
    val published: kotlin.Boolean? = null,
    @SerializedName("order")
    val order: kotlin.Int? = null
)

