/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AuditableEntity
import org.openapitools.client.models.DealPackage
import org.openapitools.client.models.Hospital
import org.openapitools.client.models.Media
import org.openapitools.client.models.Patient
import org.openapitools.client.models.QuestionComment
import org.openapitools.client.models.QuestionStatus
import org.openapitools.client.models.QuestionType

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param title 
 * @param normalizedTitle 
 * @param body 
 * @param questionType 
 * @param questionStatus 
 * @param patientId 
 * @param patient 
 * @param hospitalId 
 * @param hospital 
 * @param dealPackageId 
 * @param dealPackage 
 * @param quantity 
 * @param questionComments 
 * @param medias 
 * @param auditableEntity 
 */

data class Question (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "normalizedTitle")
    val normalizedTitle: kotlin.String? = null,
    @Json(name = "body")
    val body: kotlin.String? = null,
    @Json(name = "questionType")
    val questionType: QuestionType? = null,
    @Json(name = "questionStatus")
    val questionStatus: QuestionStatus? = null,
    @Json(name = "patientId")
    val patientId: java.util.UUID? = null,
    @Json(name = "patient")
    val patient: Patient? = null,
    @Json(name = "hospitalId")
    val hospitalId: java.util.UUID? = null,
    @Json(name = "hospital")
    val hospital: Hospital? = null,
    @Json(name = "dealPackageId")
    val dealPackageId: java.util.UUID? = null,
    @Json(name = "dealPackage")
    val dealPackage: DealPackage? = null,
    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,
    @Json(name = "questionComments")
    val questionComments: kotlin.collections.List<QuestionComment>? = null,
    @Json(name = "medias")
    val medias: kotlin.collections.List<Media>? = null,
    @Json(name = "auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

