/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.HospitalSearchItemViewModel

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param specialtyTypeId 
 * @param specialtyTypeName 
 * @param slug 
 * @param description 
 * @param content 
 * @param specialtyTypeCategoryId 
 * @param specialtyTypeCategoryName 
 * @param marketingType 
 * @param order 
 * @param hospitals 
 */

data class SpecialtyTypeSearchViewModel (
    @SerializedName("specialtyTypeId")
    val specialtyTypeId: kotlin.String? = null,
    @SerializedName("specialtyTypeName")
    val specialtyTypeName: kotlin.String? = null,
    @SerializedName("slug")
    val slug: kotlin.String? = null,
    @SerializedName("description")
    val description: kotlin.String? = null,
    @SerializedName("content")
    val content: kotlin.String? = null,
    @SerializedName("specialtyTypeCategoryId")
    val specialtyTypeCategoryId: kotlin.String? = null,
    @SerializedName("specialtyTypeCategoryName")
    val specialtyTypeCategoryName: kotlin.String? = null,
    @SerializedName("marketingType")
    val marketingType: kotlin.Int? = null,
    @SerializedName("order")
    val order: kotlin.Int? = null,
    @SerializedName("hospitals")
    val hospitals: kotlin.collections.List<HospitalSearchItemViewModel>? = null
)

