/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ArticleTag
import org.openapitools.client.models.YoutubeTag

import com.squareup.moshi.Json

/**
 * 
 * @param tagId 
 * @param normalizedTagId 
 * @param articleTags 
 * @param youtubeTags 
 */

data class Tag (
    @Json(name = "tagId")
    val tagId: kotlin.String? = null,
    @Json(name = "normalizedTagId")
    val normalizedTagId: kotlin.String? = null,
    @Json(name = "articleTags")
    val articleTags: kotlin.collections.List<ArticleTag>? = null,
    @Json(name = "youtubeTags")
    val youtubeTags: kotlin.collections.List<YoutubeTag>? = null
)

