/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AuditableEntity
import org.openapitools.client.models.MarketingType
import org.openapitools.client.models.Procedure

import com.google.gson.annotations.SerializedName
/**
 * 
 * @param name 
 * @param slug 
 * @param description 
 * @param hospitalName 
 * @param specialtyTypeId 
 * @param specialtyTypeName 
 * @param specialtyName 
 * @param marketingType 
 * @param procedure 
 * @param minPrice 
 * @param maxPrice 
 * @param priceReuqest 
 * @param order 
 * @param auditableEntity 
 */

data class UpdateServiceCommand (
    @SerializedName("name")
    val name: kotlin.String? = null,
    @SerializedName("slug")
    val slug: kotlin.String? = null,
    @SerializedName("description")
    val description: kotlin.String? = null,
    @SerializedName("hospitalName")
    val hospitalName: kotlin.String? = null,
    @SerializedName("specialtyTypeId")
    val specialtyTypeId: java.util.UUID? = null,
    @SerializedName("specialtyTypeName")
    val specialtyTypeName: kotlin.String? = null,
    @SerializedName("specialtyName")
    val specialtyName: kotlin.String? = null,
    @SerializedName("marketingType")
    val marketingType: MarketingType? = null,
    @SerializedName("procedure")
    val procedure: Procedure? = null,
    @SerializedName("minPrice")
    val minPrice: kotlin.Double? = null,
    @SerializedName("maxPrice")
    val maxPrice: kotlin.Double? = null,
    @SerializedName("priceReuqest")
    val priceReuqest: kotlin.Boolean? = null,
    @SerializedName("order")
    val order: kotlin.Int? = null,
    @SerializedName("auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

