/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AuditableEntity

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param content 
 * @param name 
 * @param slug 
 * @param description 
 * @param specialtyTypeId 
 * @param specialtyTypeName 
 * @param auditableEntity 
 */

data class UpdateSpecialtyCommand (
    @SerializedName("content")
    val content: kotlin.String? = null,
    @SerializedName("name")
    val name: kotlin.String? = null,
    @SerializedName("slug")
    val slug: kotlin.String? = null,
    @SerializedName("description")
    val description: kotlin.String? = null,
    @SerializedName("specialtyTypeId")
    val specialtyTypeId: java.util.UUID? = null,
    @SerializedName("specialtyTypeName")
    val specialtyTypeName: kotlin.String? = null,
    @SerializedName("auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

