/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param messageId 
 * @param type 
 * @param customType 
 * @param channelUrl 
 * @param mentionType 
 * @param isRemoved 
 * @param message 
 * @param data 
 * @param createdAt 
 * @param updatedAt 
 */

data class AdminMessageViewModel (
    @SerializedName("message_id")
    val messageId: kotlin.Int? = null,
    @SerializedName("type")
    val type: kotlin.String? = null,
    @SerializedName("custom_type")
    val customType: kotlin.String? = null,
    @SerializedName("channel_url")
    val channelUrl: kotlin.String? = null,
    @SerializedName("mention_type")
    val mentionType: kotlin.String? = null,
    @SerializedName("is_removed")
    val isRemoved: kotlin.Boolean? = null,
    @SerializedName("message")
    val message: kotlin.String? = null,
    @SerializedName("data")
    val data: kotlin.String? = null,
    @SerializedName("created_at")
    val createdAt: kotlin.Long? = null,
    @SerializedName("updated_at")
    val updatedAt: kotlin.Int? = null
)

