/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.ArticleContributor
import CloudHospitalApi.models.ArticleSource
import CloudHospitalApi.models.ArticleStatus
import CloudHospitalApi.models.ArticleTag
import CloudHospitalApi.models.AuditableEntity
import CloudHospitalApi.models.Hospital
import CloudHospitalApi.models.MarketingType
import CloudHospitalApi.models.Media
import CloudHospitalApi.models.User

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param title 
 * @param normalizedTitle 
 * @param slug 
 * @param description 
 * @param body 
 * @param status 
 * @param marketingType 
 * @param userId 
 * @param user 
 * @param hospitalId 
 * @param hospital 
 * @param youtubeUrl 
 * @param articleTags 
 * @param articleSources 
 * @param articleContributors 
 * @param medias 
 * @param auditableEntity 
 */

data class Article (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "normalizedTitle")
    val normalizedTitle: kotlin.String? = null,
    @Json(name = "slug")
    val slug: kotlin.String? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "body")
    val body: kotlin.String? = null,
    @Json(name = "status")
    val status: ArticleStatus? = null,
    @Json(name = "marketingType")
    val marketingType: MarketingType? = null,
    @Json(name = "userId")
    val userId: java.util.UUID? = null,
    @Json(name = "user")
    val user: User? = null,
    @Json(name = "hospitalId")
    val hospitalId: java.util.UUID? = null,
    @Json(name = "hospital")
    val hospital: Hospital? = null,
    @Json(name = "youtubeUrl")
    val youtubeUrl: kotlin.String? = null,
    @Json(name = "articleTags")
    val articleTags: kotlin.collections.List<ArticleTag>? = null,
    @Json(name = "articleSources")
    val articleSources: kotlin.collections.List<ArticleSource>? = null,
    @Json(name = "articleContributors")
    val articleContributors: kotlin.collections.List<ArticleContributor>? = null,
    @Json(name = "medias")
    val medias: kotlin.collections.List<Media>? = null,
    @Json(name = "auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

