/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.ContributionType

import com.squareup.moshi.Json

/**
 * 
 * @param contributorId 
 * @param contributorName 
 * @param contributorSlug 
 * @param contributorEmail 
 * @param contributorPhoto 
 * @param contributorDescription 
 * @param type 
 * @param filter 
 * @param order 
 */

data class ArticleContributorItemViewModel (
    @Json(name = "contributorId")
    val contributorId: java.util.UUID? = null,
    @Json(name = "contributorName")
    val contributorName: kotlin.String? = null,
    @Json(name = "contributorSlug")
    val contributorSlug: kotlin.String? = null,
    @Json(name = "contributorEmail")
    val contributorEmail: kotlin.String? = null,
    @Json(name = "contributorPhoto")
    val contributorPhoto: kotlin.String? = null,
    @Json(name = "contributorDescription")
    val contributorDescription: kotlin.String? = null,
    @Json(name = "type")
    val type: ContributionType? = null,
    @Json(name = "filter")
    val filter: kotlin.String? = null,
    @Json(name = "order")
    val order: kotlin.Int? = null
)

