/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 * @param hospitals 
 * @param doctors 
 * @param deals 
 * @param specialties 
 * @param specialtyTypes 
 */

data class AzureSearchViewModel (
    @SerializedName("hospitals")
    val hospitals: kotlin.Int? = null,
    @SerializedName("doctors")
    val doctors: kotlin.Int? = null,
    @SerializedName("deals")
    val deals: kotlin.Int? = null,
    @SerializedName("specialties")
    val specialties: kotlin.Int? = null,
    @SerializedName("specialtyTypes")
    val specialtyTypes: kotlin.Int? = null
)

