/**
 * Swagger UI - Cloud Hospital Api-INT
 *
 * Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
 *
 * The version of the OpenAPI document: 2
 * Contact: hyounoosung@icloudhospital.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package CloudHospitalApi.models

import CloudHospitalApi.models.ConsultationStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param actorId 
 * @param createdDate 
 * @param actorName 
 */
@JsonClass(generateAdapter = true)
data class ConsultationChangeLogModel (

    @Json(name = "status")
    val status: ConsultationStatus? = null,

    @Json(name = "actorId")
    val actorId: java.util.UUID? = null,

    @Json(name = "createdDate")
    val createdDate: java.time.LocalDateTime? = null,

    @Json(name = "actorName")
    val actorName: kotlin.String? = null

)

