/**
 * Swagger UI - Cloud Hospital Api-INT
 *
 * Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
 *
 * The version of the OpenAPI document: 2
 * Contact: hyounoosung@icloudhospital.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package CloudHospitalApi.models

import CloudHospitalApi.models.ConsultationTimetableStatus
import CloudHospitalApi.models.ConsultationTimetableTimeSlotModel
import CloudHospitalApi.models.DayOfWeek

import com.squareup.moshi.Json

/**
 * 
 *
 * @param date 
 * @param dayOfWeek 
 * @param status 
 * @param isAvailable 
 * @param slots 
 * @param hasTimeSlotItems 
 */

data class ConsultationTimetableDateModel (

    @Json(name = "date")
    val date: java.time.LocalDateTime? = null,

    @Json(name = "dayOfWeek")
    val dayOfWeek: DayOfWeek? = null,

    @Json(name = "status")
    val status: ConsultationTimetableStatus? = null,

    @Json(name = "isAvailable")
    val isAvailable: kotlin.Boolean? = null,

    @Json(name = "slots")
    val slots: kotlin.collections.List<ConsultationTimetableTimeSlotModel>? = null,

    @Json(name = "hasTimeSlotItems")
    val hasTimeSlotItems: kotlin.Boolean? = null

)

