/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.MediaViewModel
import CloudHospitalApi.models.QuestionStatus
import CloudHospitalApi.models.QuestionType

import com.squareup.moshi.Json

/**
 * 
 * @param title 
 * @param body 
 * @param questionType 
 * @param questionStatus 
 * @param dealPackageId 
 * @param quantity 
 * @param medias 
 */

data class CreateQuestionCommand (
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "body")
    val body: kotlin.String? = null,
    @Json(name = "questionType")
    val questionType: QuestionType? = null,
    @Json(name = "questionStatus")
    val questionStatus: QuestionStatus? = null,
    @Json(name = "dealPackageId")
    val dealPackageId: java.util.UUID? = null,
    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,
    @Json(name = "medias")
    val medias: kotlin.collections.List<MediaViewModel>? = null
)

