/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 2
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models


import com.squareup.moshi.Json

/**
 * 
 * @param dealId 
 * @param dealName 
 * @param serviceId 
 * @param serviceName 
 * @param order 
 */

data class DealServiceModel (
    @Json(name = "dealId")
    val dealId: java.util.UUID? = null,
    @Json(name = "dealName")
    val dealName: kotlin.String? = null,
    @Json(name = "serviceId")
    val serviceId: java.util.UUID? = null,
    @Json(name = "serviceName")
    val serviceName: kotlin.String? = null,
    @Json(name = "order")
    val order: kotlin.Int? = null
)

