/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.Procedure

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param dealPackageId 
 * @param serviceId 
 * @param serviceName 
 * @param procedure 
 * @param order 
 */

data class DealPackageServiceItemViewModel (
    @SerializedName("dealPackageId")
    val dealPackageId: java.util.UUID? = null,
    @SerializedName("serviceId")
    val serviceId: java.util.UUID? = null,
    @SerializedName("serviceName")
    val serviceName: kotlin.String? = null,
    @SerializedName("procedure")
    val procedure: Procedure? = null,
    @SerializedName("order")
    val order: kotlin.Int? = null
)

