/**
 * Swagger UI - Cloud Hospital Api-INT
 *
 * Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
 *
 * The version of the OpenAPI document: 2
 * Contact: hyounoosung@icloudhospital.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package CloudHospitalApi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param languageCode 
 * @param dealId 
 * @param dealName 
 * @param dealSlug 
 * @param serviceId 
 * @param serviceName 
 * @param serviceSlug 
 * @param order 
 */

data class DealServiceItemModel (

    @Json(name = "languageCode")
    val languageCode: kotlin.String? = null,

    @Json(name = "dealId")
    val dealId: java.util.UUID? = null,

    @Json(name = "dealName")
    val dealName: kotlin.String? = null,

    @Json(name = "dealSlug")
    val dealSlug: kotlin.String? = null,

    @Json(name = "serviceId")
    val serviceId: java.util.UUID? = null,

    @Json(name = "serviceName")
    val serviceName: kotlin.String? = null,

    @Json(name = "serviceSlug")
    val serviceSlug: kotlin.String? = null,

    @Json(name = "order")
    val order: kotlin.Int? = null

)

