/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.AuditableEntity
import CloudHospitalApi.models.Booking
import CloudHospitalApi.models.Deal
import CloudHospitalApi.models.DealPackageService
import CloudHospitalApi.models.Manager
import CloudHospitalApi.models.Question
import CloudHospitalApi.models.RefundPolicy

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param id 
 * @param dealId 
 * @param deal 
 * @param refundPolicy 
 * @param additionalServices 
 * @param accomodation 
 * @param transfer 
 * @param bonus 
 * @param price 
 * @param dealPackageServices 
 * @param managers 
 * @param questions 
 * @param bookings 
 * @param auditableEntity 
 */

data class DealPackage (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("dealId")
    val dealId: java.util.UUID? = null,
    @SerializedName("deal")
    val deal: Deal? = null,
    @SerializedName("refundPolicy")
    val refundPolicy: RefundPolicy? = null,
    @SerializedName("additionalServices")
    val additionalServices: kotlin.String? = null,
    @SerializedName("accomodation")
    val accomodation: kotlin.String? = null,
    @SerializedName("transfer")
    val transfer: kotlin.String? = null,
    @SerializedName("bonus")
    val bonus: kotlin.String? = null,
    @SerializedName("price")
    val price: kotlin.Double? = null,
    @SerializedName("dealPackageServices")
    val dealPackageServices: kotlin.collections.List<DealPackageService>? = null,
    @SerializedName("managers")
    val managers: kotlin.collections.List<Manager>? = null,
    @SerializedName("questions")
    val questions: kotlin.collections.List<Question>? = null,
    @SerializedName("bookings")
    val bookings: kotlin.collections.List<Booking>? = null,
    @SerializedName("auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

