/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.Hospital

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param id 
 * @param hospitalId 
 * @param hospital 
 * @param name 
 * @param normalizedName 
 * @param additionalInfo 
 */

data class Department (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("hospitalId")
    val hospitalId: java.util.UUID? = null,
    @SerializedName("hospital")
    val hospital: Hospital? = null,
    @SerializedName("name")
    val name: kotlin.String? = null,
    @SerializedName("normalizedName")
    val normalizedName: kotlin.String? = null,
    @SerializedName("additionalInfo")
    val additionalInfo: kotlin.String? = null
)

