/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.AuditableEntity
import CloudHospitalApi.models.Device
import CloudHospitalApi.models.Location

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param id 
 * @param deviceId 
 * @param device 
 * @param version 
 * @param location 
 * @param auditableEntity 
 */

data class DeviceLogin (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("deviceId")
    val deviceId: java.util.UUID? = null,
    @SerializedName("device")
    val device: Device? = null,
    @SerializedName("version")
    val version: kotlin.String? = null,
    @SerializedName("location")
    val location: Location? = null,
    @SerializedName("auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

