/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.AuditableEntity
import CloudHospitalApi.models.DeviceLogin
import CloudHospitalApi.models.Platform
import CloudHospitalApi.models.User

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param id 
 * @param token 
 * @param platform 
 * @param appAlert 
 * @param eventAlert 
 * @param noticeAlert 
 * @param userId 
 * @param user 
 * @param deviceLogins 
 * @param auditableEntity 
 */

data class Device (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("token")
    val token: kotlin.String? = null,
    @SerializedName("platform")
    val platform: Platform? = null,
    @SerializedName("appAlert")
    val appAlert: kotlin.Boolean? = null,
    @SerializedName("eventAlert")
    val eventAlert: kotlin.Boolean? = null,
    @SerializedName("noticeAlert")
    val noticeAlert: kotlin.Boolean? = null,
    @SerializedName("userId")
    val userId: java.util.UUID? = null,
    @SerializedName("user")
    val user: User? = null,
    @SerializedName("deviceLogins")
    val deviceLogins: kotlin.collections.List<DeviceLogin>? = null,
    @SerializedName("auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

