/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.Article
import CloudHospitalApi.models.AuditableEntity
import CloudHospitalApi.models.AwardViewModel
import CloudHospitalApi.models.DoctorCertificateItemViewModel
import CloudHospitalApi.models.DoctorEducationItemViewModel
import CloudHospitalApi.models.DoctorPortfolioItemViewModel
import CloudHospitalApi.models.DoctorReviewItemViewModel
import CloudHospitalApi.models.DoctorSpecialtyItemViewModel
import CloudHospitalApi.models.Gender
import CloudHospitalApi.models.HospitalAffiliationViewModel
import CloudHospitalApi.models.MediaViewModel
import CloudHospitalApi.models.UserLanguageViewModel
import CloudHospitalApi.models.UserLocationViewModel

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param userName 
 * @param firstName 
 * @param lastName 
 * @param fullname 
 * @param phone 
 * @param email 
 * @param photo 
 * @param photoThumbnail 
 * @param gender 
 * @param dateOfBirth 
 * @param timeZone 
 * @param communicationUserId 
 * @param auditableEntity 
 * @param userType 
 * @param languages 
 * @param locations 
 * @param slug 
 * @param startPracticeDate 
 * @param yearOfExperience 
 * @param overview 
 * @param consultationEnabled 
 * @param consultationFee 
 * @param doctorReviews 
 * @param doctorEducations 
 * @param doctorPortfolios 
 * @param doctorSpecialties 
 * @param doctorCertificates 
 * @param doctorAffiliations 
 * @param articles 
 * @param awards 
 * @param medias 
 */

data class DoctorViewModel (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "userName")
    val userName: kotlin.String? = null,
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,
    @Json(name = "fullname")
    val fullname: kotlin.String? = null,
    @Json(name = "phone")
    val phone: kotlin.String? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "photo")
    val photo: kotlin.String? = null,
    @Json(name = "photoThumbnail")
    val photoThumbnail: kotlin.String? = null,
    @Json(name = "gender")
    val gender: Gender? = null,
    @Json(name = "dateOfBirth")
    val dateOfBirth: java.time.LocalDateTime? = null,
    @Json(name = "timeZone")
    val timeZone: kotlin.String? = null,
    @Json(name = "communicationUserId")
    val communicationUserId: kotlin.String? = null,
    @Json(name = "auditableEntity")
    val auditableEntity: AuditableEntity? = null,
    @Json(name = "userType")
    val userType: kotlin.String? = null,
    @Json(name = "languages")
    val languages: kotlin.collections.List<UserLanguageViewModel>? = null,
    @Json(name = "locations")
    val locations: kotlin.collections.List<UserLocationViewModel>? = null,
    @Json(name = "slug")
    val slug: kotlin.String? = null,
    @Json(name = "startPracticeDate")
    val startPracticeDate: java.time.LocalDateTime? = null,
    @Json(name = "yearOfExperience")
    val yearOfExperience: kotlin.Double? = null,
    @Json(name = "overview")
    val overview: kotlin.String? = null,
    @Json(name = "consultationEnabled")
    val consultationEnabled: kotlin.Boolean? = null,
    @Json(name = "consultationFee")
    val consultationFee: kotlin.Double? = null,
    @Json(name = "doctorReviews")
    val doctorReviews: kotlin.collections.List<DoctorReviewItemViewModel>? = null,
    @Json(name = "doctorEducations")
    val doctorEducations: kotlin.collections.List<DoctorEducationItemViewModel>? = null,
    @Json(name = "doctorPortfolios")
    val doctorPortfolios: kotlin.collections.List<DoctorPortfolioItemViewModel>? = null,
    @Json(name = "doctorSpecialties")
    val doctorSpecialties: kotlin.collections.List<DoctorSpecialtyItemViewModel>? = null,
    @Json(name = "doctorCertificates")
    val doctorCertificates: kotlin.collections.List<DoctorCertificateItemViewModel>? = null,
    @Json(name = "doctorAffiliations")
    val doctorAffiliations: kotlin.collections.List<HospitalAffiliationViewModel>? = null,
    @Json(name = "articles")
    val articles: kotlin.collections.List<Article>? = null,
    @Json(name = "awards")
    val awards: kotlin.collections.List<AwardViewModel>? = null,
    @Json(name = "medias")
    val medias: kotlin.collections.List<MediaViewModel>? = null
)

