/**
 * Swagger UI - Cloud Hospital Api-INT
 *
 * Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
 *
 * The version of the OpenAPI document: 2
 * Contact: hyounoosung@icloudhospital.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package CloudHospitalApi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param language 
 * @param userId 
 */
@JsonClass(generateAdapter = true)
data class DoctorLanguageModel (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "language")
    val language: kotlin.String? = null,

    @Json(name = "userId")
    val userId: java.util.UUID? = null

)

