/**
 * Swagger UI - Cloud Hospital Api-INT
 *
 * Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
 *
 * The version of the OpenAPI document: 2
 * Contact: hyounoosung@icloudhospital.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package CloudHospitalApi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: photo,video,youtube,document,frontal,diagonal,side
 */

enum class MediaType(val value: kotlin.String) {

    @Json(name = "Photo")
    photo("Photo"),

    @Json(name = "Video")
    video("Video"),

    @Json(name = "Youtube")
    youtube("Youtube"),

    @Json(name = "Document")
    document("Document"),

    @Json(name = "Frontal")
    frontal("Frontal"),

    @Json(name = "Diagonal")
    diagonal("Diagonal"),

    @Json(name = "Side")
    side("Side");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MediaType) "$data" else null

        /**
         * Returns a valid [MediaType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MediaType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

