/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.PlanViewModel
import CloudHospitalApi.models.SubscriptionViewModel

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param planId 
 * @param plan 
 * @param isActive 
 * @param isOwner 
 * @param enableInvite 
 * @param subscription 
 */

data class MembershipViewModel (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "planId")
    val planId: java.util.UUID? = null,
    @Json(name = "plan")
    val plan: PlanViewModel? = null,
    @Json(name = "isActive")
    val isActive: kotlin.Boolean? = null,
    @Json(name = "isOwner")
    val isOwner: kotlin.Boolean? = null,
    @Json(name = "enableInvite")
    val enableInvite: kotlin.Boolean? = null,
    @Json(name = "subscription")
    val subscription: SubscriptionViewModel? = null
)

