/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.AuditableEntity
import CloudHospitalApi.models.MediaViewModel
import CloudHospitalApi.models.QuestionStatus
import CloudHospitalApi.models.QuestionType
import CloudHospitalApi.models.RefundPolicy

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param title 
 * @param userId 
 * @param userName 
 * @param fullName 
 * @param hospitalId 
 * @param hospitalName 
 * @param questionType 
 * @param questionStatus 
 * @param questionCommentsCount 
 * @param dealId 
 * @param dealName 
 * @param dealPackageId 
 * @param refundPolicy 
 * @param quantity 
 * @param auditableEntity 
 * @param body 
 * @param medias 
 */

data class QuestionViewModel (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "userId")
    val userId: java.util.UUID? = null,
    @Json(name = "userName")
    val userName: kotlin.String? = null,
    @Json(name = "fullName")
    val fullName: kotlin.String? = null,
    @Json(name = "hospitalId")
    val hospitalId: java.util.UUID? = null,
    @Json(name = "hospitalName")
    val hospitalName: kotlin.String? = null,
    @Json(name = "questionType")
    val questionType: QuestionType? = null,
    @Json(name = "questionStatus")
    val questionStatus: QuestionStatus? = null,
    @Json(name = "questionCommentsCount")
    val questionCommentsCount: kotlin.Int? = null,
    @Json(name = "dealId")
    val dealId: java.util.UUID? = null,
    @Json(name = "dealName")
    val dealName: kotlin.String? = null,
    @Json(name = "dealPackageId")
    val dealPackageId: java.util.UUID? = null,
    @Json(name = "refundPolicy")
    val refundPolicy: RefundPolicy? = null,
    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,
    @Json(name = "auditableEntity")
    val auditableEntity: AuditableEntity? = null,
    @Json(name = "body")
    val body: kotlin.String? = null,
    @Json(name = "medias")
    val medias: kotlin.collections.List<MediaViewModel>? = null
)

