/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models


import com.squareup.moshi.Json

/**
 * 
 * @param userId 
 * @param nickname 
 * @param profileUrl 
 */

data class SendBirdGroupChannelrOperator (
    @Json(name = "user_id")
    val userId: kotlin.String? = null,
    @Json(name = "nickname")
    val nickname: kotlin.String? = null,
    @Json(name = "profile_url")
    val profileUrl: kotlin.String? = null
)

