/**
* Swagger UI - Cloud Hospital Api-INT
* Cloud Hospital application with Swagger, Swashbuckle, and API versioning.
*
* The version of the OpenAPI document: 1
* Contact: hyounoosung@icloudhospital.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package CloudHospitalApi.models

import CloudHospitalApi.models.AuditableEntity
import CloudHospitalApi.models.HospitalSpecialty
import CloudHospitalApi.models.Media
import CloudHospitalApi.models.Procedure

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param name 
 * @param normalizedName 
 * @param slug 
 * @param description 
 * @param content 
 * @param normalizedDescription 
 * @param hospitalId 
 * @param specialtyId 
 * @param packageServiceId 
 * @param hospitalSpecialty 
 * @param procedure 
 * @param serviceCategoryId 
 * @param minPrice 
 * @param maxPrice 
 * @param priceReuqest 
 * @param order 
 * @param medias 
 * @param auditableEntity 
 */

data class Service (
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "normalizedName")
    val normalizedName: kotlin.String? = null,
    @Json(name = "slug")
    val slug: kotlin.String? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "content")
    val content: kotlin.String? = null,
    @Json(name = "normalizedDescription")
    val normalizedDescription: kotlin.String? = null,
    @Json(name = "hospitalId")
    val hospitalId: java.util.UUID? = null,
    @Json(name = "specialtyId")
    val specialtyId: java.util.UUID? = null,
    @Json(name = "packageServiceId")
    val packageServiceId: java.util.UUID? = null,
    @Json(name = "hospitalSpecialty")
    val hospitalSpecialty: HospitalSpecialty? = null,
    @Json(name = "procedure")
    val procedure: Procedure? = null,
    @Json(name = "serviceCategoryId")
    val serviceCategoryId: java.util.UUID? = null,
    @Json(name = "minPrice")
    val minPrice: kotlin.Double? = null,
    @Json(name = "maxPrice")
    val maxPrice: kotlin.Double? = null,
    @Json(name = "priceReuqest")
    val priceReuqest: kotlin.Boolean? = null,
    @Json(name = "order")
    val order: kotlin.Int? = null,
    @Json(name = "medias")
    val medias: kotlin.collections.List<Media>? = null,
    @Json(name = "auditableEntity")
    val auditableEntity: AuditableEntity? = null
)

